package oracle.summitdi.model.queries.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 22 17:51:39 PDT 2012
// ---------------------------------------------------------------------
public interface CustomersView extends ViewObject {
  void executeCountriesQuery(String searchTerm);

  void resetQueryValues();
}
