package oracle.summitdi.model.queries;

import oracle.summitdi.base.SummitViewObjectImpl;
import oracle.summitdi.model.queries.common.CustomersView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 22 14:38:39 PDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustomersViewImpl extends SummitViewObjectImpl implements CustomersView {
  /**
   * This is the default constructor (do not remove).
   */
  public CustomersViewImpl() {
  }
  
  public void executeCountriesQuery(String searchTerm){
    if(searchTerm !=null && searchTerm.length()>0){
      removeApplyViewCriteriaName("CustomersByCountry");
      setcountry_var(searchTerm);
      setApplyViewCriteriaName("CustomersByCountry");
      executeQuery();
    }
  }
   
  public void resetQueryValues(){
    removeApplyViewCriteriaName("CustomersByCountry");
    executeQuery();
  }


  /**
   * Returns the variable value for country_var.
   * @return variable value for country_var
   */
  public String getcountry_var() {
    return (String)ensureVariableManager().getVariableValue("country_var");
  }

  /**
   * Sets <code>value</code> for variable country_var.
   * @param value value to bind as country_var
   */
  public void setcountry_var(String value) {
    ensureVariableManager().setVariableValue("country_var", value);
  }
}
